language: rust

cache:
  cargo: true

matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly

branches:
  only:
    - "master"

script:
  - rustc --version
  - cargo test